                                            Робота з матрицями і таблицями 
                                            
1. Виконати дії з векторами і матрицями:

a. Створити квадратну матрицю (n × n), заповнити її за правилом з таблиці
варіантів. Знайти детермінант матриці і обернену до неї матрицю.

b. Задати два вектори з n елементами, заповнені випадковими числами: один –
дійсними числами, другий – цілими числами. Обчислити їх суму і добуток.

c. Задати дві матриці, заповнені випадковими числами: одна розміру n × m, друга
– m × n. Знайти їх добуток.

d. Знайти добуток матриць і векторів (розбити на дві пари, для яких можливо
виконання операції).

In [11]:
import numpy as np

In [74]:
n = 3
m = 5
matrix = np.zeros((n,n))
for i in range(n):
    for j in range(n):
        matrix[i][j] = pow((2 * i - j), 2 - j)
print("Our matrix:\n", matrix)
print("Det:", np.linalg.det(matrix))
print("Inverse:\n", np.linalg.inv(matrix))

Our matrix:
 [[ 0. -1.  1.]
 [ 4.  1.  1.]
 [16.  3.  1.]]
Det: -15.999999999999998
Inverse:
 [[ 0.125 -0.25   0.125]
 [-0.75   1.    -0.25 ]
 [ 0.25   1.    -0.25 ]]


In [75]:
v1 = np.random.randn(n)
print("v1 = ", v1)
v2 = np.random.default_rng().integers(97, size = n)
print("v2 = ", v2)
print("Sum: ", v1+v2)
print("Multiplication: ", np.dot(v1, v2))

v1 =  [-0.46669321 -1.13295762  0.31821513]
v2 =  [33 67  3]
Sum:  [32.53330679 65.86704238  3.31821513]
Multiplication:  -90.35439103726358


In [76]:
M1 = np.random.randn(n,m)
M2 = np.random.randn(m,n)
print("M1:\n", M1)
print("M2:\n", M2)
print("Multiplication M1 * M2:\n", np.dot(M1, M2))
print("Multiplication M2 * M1:\n", np.dot(M2, M1))

M1:
 [[ 0.2932003  -0.60992901  0.48490096  0.91431811  0.82747874]
 [-0.06996301 -1.33450343 -1.38009207 -0.0798065   1.90047167]
 [-0.74604632  0.82646494 -0.42316429  0.14397976 -1.49583764]]
M2:
 [[ 1.20144892  2.32715018 -0.55598701]
 [-0.75966163 -0.40794326  2.05450993]
 [ 0.84037629  0.22930587 -0.194758  ]
 [-0.60348322 -1.18997063  1.55873102]
 [ 0.07485585 -1.87609611 -0.75739424]]
Multiplication M1 * M2:
 [[ 0.7332701  -1.59811316 -0.71211074]
 [-0.03965927 -3.40537606 -3.99787122]
 [-2.07864906  0.46465681  3.55255165]]
Multiplication M2 * M1:
 [[ 0.60424282 -4.29789221 -2.39382391  0.83273391  6.24852272]
 [-1.72695165  2.70572177 -0.67475664 -0.36620802 -4.47710173]
 [ 0.37565414 -0.97954     0.1734507   0.72202995  1.42250916]
 [-1.25657307  3.24433835  0.69004012 -0.23238253 -5.09248353]
 [ 0.71825627  1.83204014  2.94598523  0.10911729 -2.37058706]]


In [50]:
print("Multiplication v1 * M1:\n", np.dot(v1, M1))
print("Multiplication v2 * M1:\n", np.dot(v2, M1))
print("Multiplication M2 * v1:\n", np.dot(M2, v1))
print("Multiplication M2 * v2:\n", np.dot(M2, v2))

Multiplication v1 * M1:
 [ 0.5052936  -0.54148279  0.61392318 -0.88660764 -2.70282409]
Multiplication v2 * M1:
 [  31.04140281    8.65853502   16.74862972   -5.46837097 -129.08896301]
Multiplication M2 * v1:
 [-2.17392348  1.2947863  -0.78870478  0.70671513  1.65947615]
Multiplication M2 * v2:
 [-102.06626988   59.59386305  -72.45480257   -7.81984453   78.21374639]


2. Виконати дії з таблицями даних:

a. Створити таблицю за описом (https://dou.ua/lenta/articles/ukrainian-universities-2023/?from=doufp). 
Таблиця має містити інформацію про назву вишу, місто розташування, відсоток студентів з високим рівнем володіння англійською мовою, рівень рекомендації студентів, відсоток випускників, які працюють в розробці, середню заробітну плату випускників. Таблиця має складатися мінімум з 15 рядків.

b. Знайти і вивести університети (назву і рейтинг) з рейтинговою оцінкою випускників вищою за 7.0.

c. Знайти і вивести університети (назву і рівень) з рівнем володіння англійською
мовою вищим 50%.

d. Визначити університет, відсоток випускників-розробників якого найвищий.

e. Знайти і вивести університети, рівень заробітної плати випускників яких нижчий за середній з рейтингу.

f. Визначити скільки університетів з кожного міста у рейтингу.


In [52]:
import pandas as pd

In [62]:
data = {
    "Rank": ["1", "2", "3-5", "3-5", "3-5", "6-7", "6-7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17",
             "18", "19", "20"],
    "University": [
        "УКУ", "ХНЕУ", "КНУ ім. Шевченка", "НаУКМА", "ОНУ ім. Мечникова", "ДУТ", "СумДУ", "НТУУ «КПІ ім. І. Сікорського»", 
        "ЛНУ ім. Франка", "ХНУРЕ", "НУ «Львівська політехніка»", "ДНУ ім. Гончара", "НТУ «Дніпровська політехніка»", 
        "ХНУ м. Хмельницький", "КНЕУ", "НУ «Одеська політехніка» (ОНПУ)", "ХАІ", "ЧНУ ім. Федьковича", "ХНУ ім. Каразіна", 
        "НТУ «ХПІ»"
    ],
    "City": ["Lviv", "Kharkiv", "Kyiv", "Kyiv", "Odesa", "Kyiv", "Sumy", "Kyiv", "Lviv", "Kharkiv", "Lviv",
               "Dnipro", "Dnipro", "Khmelnytskyi", "Kyiv", "Odesa", "Kharkiv", "Chernivtsi", "Kharkiv", "Kharkiv"],
    "Developer Salary($)": [3700, 2950, 2950, 2650, 2850, 2950, 3000, 3000, 2800, 2950, 2850, 3000, 2700, 2900,
                             2800, 2900, 2800, 2600, 2700, 2700],
    "English Level(%)": [83, 56, 73, 79, 70, 46, 43, 58, 63, 53, 58, 48, 51, 48, 59, 48, 41, 42, 59, 42],
    "Student Recommendation": [9.3, 8.3, 6.7, 8.7, 7.2, 6.4, 6.4, 7.1, 6.8, 6.9, 6.4, 7.4, 6.7, 6.3, 5.6, 6.4, 7.3,
                               8.4, 5.5, 7.3],
    "Graduates-developers(%)": [1, 1, 6, 2, 1, 1, 1, 13, 4, 4, 9, 2, 1, 1, 2, 1, 1, 1, 2, 2]
}
uni_info = pd.DataFrame(data)
uni_info

Rank                       University          City  Developer Salary($)  \
0     1                              УКУ          Lviv                 3700   
1     2                             ХНЕУ       Kharkiv                 2950   
2   3-5                 КНУ ім. Шевченка          Kyiv                 2950   
3   3-5                           НаУКМА          Kyiv                 2650   
4   3-5                ОНУ ім. Мечникова         Odesa                 2850   
5   6-7                              ДУТ          Kyiv                 2950   
6   6-7                            СумДУ          Sumy                 3000   
7     8    НТУУ «КПІ ім. І. Сікорського»          Kyiv                 3000   
8     9                   ЛНУ ім. Франка          Lviv                 2800   
9    10                            ХНУРЕ       Kharkiv                 2950   
10   11       НУ «Львівська політехніка»          Lviv                 2850   
11   12                  ДНУ ім. Гончара        Dnipro                 3000   
12   13    НТУ «Дніпровська політехніка»        Dnipro                 2700   
13   14              ХНУ м. Хмельницький  Khmelnytskyi                 2900   
14   15                             КНЕУ          Kyiv                 2800   
15   16  НУ «Одеська політехніка» (ОНПУ)         Odesa                 2900   
16   17                              ХАІ       Kharkiv                 2800   
17   18               ЧНУ ім. Федьковича    Chernivtsi                 2600   
18   19                 ХНУ ім. Каразіна       Kharkiv                 2700   
19   20                        НТУ «ХПІ»       Kharkiv                 2700   

    English Level(%)  Student Recommendation  Graduates-developers(%)  
0                 83                     9.3                        1  
1                 56                     8.3                        1  
2                 73                     6.7                        6  
3                 79                     8.7                        2  
4                 70                     7.2                        1  
5                 46                     6.4                        1  
6                 43                     6.4                        1  
7                 58                     7.1                       13  
8                 63                     6.8                        4  
9                 53                     6.9                        4  
10                58                     6.4                        9  
11                48                     7.4                        2  
12                51                     6.7                        1  
13                48                     6.3                        1  
14                59                     5.6                        2  
15                48                     6.4                        1  
16                41                     7.3                        1  
17                42                     8.4                        1  
18                59                     5.5                        2  
19                42                     7.3                        2

In [65]:
high_student_recommendation = uni_info[uni_info["Student Recommendation"] > 7.0][["Rank", "University", "Student Recommendation"]]
high_student_recommendation

Rank                     University  Student Recommendation
0     1                            УКУ                     9.3
1     2                           ХНЕУ                     8.3
3   3-5                         НаУКМА                     8.7
4   3-5              ОНУ ім. Мечникова                     7.2
7     8  НТУУ «КПІ ім. І. Сікорського»                     7.1
11   12                ДНУ ім. Гончара                     7.4
16   17                            ХАІ                     7.3
17   18             ЧНУ ім. Федьковича                     8.4
19   20                      НТУ «ХПІ»                     7.3

In [66]:
high_english_level = uni_info[uni_info["English Level(%)"] > 50][["University", "English Level(%)"]]
high_english_level

University  English Level(%)
0                             УКУ                83
1                            ХНЕУ                56
2                КНУ ім. Шевченка                73
3                          НаУКМА                79
4               ОНУ ім. Мечникова                70
7   НТУУ «КПІ ім. І. Сікорського»                58
8                  ЛНУ ім. Франка                63
9                           ХНУРЕ                53
10     НУ «Львівська політехніка»                58
12  НТУ «Дніпровська політехніка»                51
14                           КНЕУ                59
18               ХНУ ім. Каразіна                59

In [69]:
max_developers = uni_info.sort_values(by = 'Graduates-developers(%)', ascending=False)
max_developers_filtered = max_developers[['University', 'Graduates-developers(%)']]
max_developers_filtered

University  Graduates-developers(%)
7     НТУУ «КПІ ім. І. Сікорського»                       13
10       НУ «Львівська політехніка»                        9
2                  КНУ ім. Шевченка                        6
8                    ЛНУ ім. Франка                        4
9                             ХНУРЕ                        4
11                  ДНУ ім. Гончара                        2
3                            НаУКМА                        2
18                 ХНУ ім. Каразіна                        2
19                        НТУ «ХПІ»                        2
14                             КНЕУ                        2
0                               УКУ                        1
1                              ХНЕУ                        1
5                               ДУТ                        1
4                 ОНУ ім. Мечникова                        1
6                             СумДУ                        1
12    НТУ «Дніпровська політехніка»                        1
15  НУ «Одеська політехніка» (ОНПУ)                        1
13              ХНУ м. Хмельницький                        1
17               ЧНУ ім. Федьковича                        1
16                              ХАІ                        1

In [71]:
average_salary = uni_info["Developer Salary($)"].mean()
low_salary_universities = uni_info[uni_info["Developer Salary($)"] < average_salary][["University", "Developer Salary($)"]]
low_salary_universities

University  Developer Salary($)
3                          НаУКМА                 2650
4               ОНУ ім. Мечникова                 2850
8                  ЛНУ ім. Франка                 2800
10     НУ «Львівська політехніка»                 2850
12  НТУ «Дніпровська політехніка»                 2700
14                           КНЕУ                 2800
16                            ХАІ                 2800
17             ЧНУ ім. Федьковича                 2600
18               ХНУ ім. Каразіна                 2700
19                      НТУ «ХПІ»                 2700

In [72]:
universities_by_city = uni_info["City"].value_counts()
universities_by_city

City
Kharkiv         5
Kyiv            5
Lviv            3
Odesa           2
Dnipro          2
Sumy            1
Khmelnytskyi    1
Chernivtsi      1
Name: count, dtype: int64